# Generated by Django 2.1.3 on 2019-08-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_auto_20190803_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userName',
            field=models.CharField(default='', max_length=10),
        ),
    ]
