# Generated by Django 2.1.3 on 2019-08-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0014_auto_20190805_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
