# Generated by Django 2.1.3 on 2019-08-08 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0016_auto_20190807_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='views',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 8, 8)),
        ),
    ]
