# Generated by Django 2.1.3 on 2019-08-09 16:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0017_auto_20190808_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardFile', models.FileField(null=True, upload_to='board/')),
                ('filename', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='File',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 8, 10)),
        ),
        migrations.AddField(
            model_name='boardfile',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='first.Board'),
        ),
    ]
