# Generated by Django 2.1.3 on 2019-08-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamproject', '0006_auto_20190730_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('content', models.CharField(max_length=50)),
                ('is_finished', models.BooleanField(default=False)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamproject.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('board_type', models.TextField(null=True)),
                ('body', models.TextField()),
                ('File', models.FileField(null=True, upload_to='teamboard/')),
                ('writer', models.CharField(default='', max_length=100)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamproject.Team')),
            ],
        ),
    ]
