# Generated by Django 2.1.3 on 2019-08-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamproject', '0007_team_todo_teamboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='refFile',
        ),
    ]
