# Generated by Django 2.1.3 on 2019-08-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamproject', '0010_auto_20190808_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamboard',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
