# Generated by Django 2.1.3 on 2019-08-09 16:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamproject', '0011_teamboard_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamFile', models.FileField(null=True, upload_to='teamboard/')),
                ('filename', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='teamboard',
            name='File',
        ),
        migrations.AlterField(
            model_name='commenttb',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 8, 10)),
        ),
        migrations.AddField(
            model_name='filetb',
            name='teamboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamboards', to='teamproject.TeamBoard'),
        ),
    ]
